services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
    networks:
      - backend-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redisinsight.rule=Host(`redisinsight.sanattudu.tech`)"
      - "traefik.http.routers.redisinsight.entrypoints=websecure"
      - "traefik.http.routers.redisinsight.tls=true"
      - "traefik.http.routers.redisinsight.tls.certresolver=letsencrypt"
      - "traefik.http.routers.redisinsight.middlewares=redisinsight-auth"
      - "traefik.http.middlewares.redisinsight-auth.basicauth.users=${REDISINSIGHT_BASIC_AUTH}"
      - "traefik.http.services.redisinsight.loadbalancer.server.port=5540"

networks:
  backend-net:
    external: true

volumes:
  redis_data:
  redisinsight_data: